#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/leds.inc

if [ ! -e "$CNF_DATADIR/Run/karotz.sleep" ]; then
   ping 8.8.8.8 -c 3 -q  >>/dev/null 2>>/dev/null
   if [ ! $? -eq 0 ]; then
     Log  "Lost Network connexion" 1
     mplayer /mnt/usbkey/Sounds/alarme.mp3 &
     Leds FF0000 0000FF 1 1 100 
     /sbin/reboot     
  else
     LedsRestore
  fi
fi
